### ISSUE TITLE
Split can affect any body

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#109]
Posting a split via the split API can change a body other than the specified one. This happens when the split is partially contained by the original body.

**Comment by DocSavage** [comment]
Rather than make the split less efficient (by making sure the POSTed split voxels are within the "from" label sparse volume), we've made it explicit in the API documentation that DVID expects the POSTed split sparse volume to *not* span multiple labels but only be a subset of the "from" label voxels.
