### ISSUE TITLE
Unify labelvol and labelblk creation

### ISSUE THREAD

**Issue by stephenplaza** [janelia-flyem/dvid#114]
When one creates a labelblk datatype, labelvol should automatically be created via an option.  While there are some good reasons to keep things like labelblk and labelvol separate since, in theory, a user might only need one type, I don't think it makes sense that an explicit creation of two instance be required.

In this scenario, I am not sure what would be the best naming mechanism to distinguish the interfaces.  I almost feel that it makes sense to support the concept that a datatype supports multiple interfaces/denormalizations (and the meta would indicate the supported interfaces or denormalizations).  Datatypes like google voxels support a special google interface + our tile interface, etc.  Labels would support labelblk, labelvol, labelsz, etc.  Not sure what is the best way to decompose different interfaces into distinct types.  For instance, labelgraph clearly wouldn't be an interface for labels even though it requires labels to exist.  Perhaps, a single datatype is used if the interfaces it defines are just different views or specializations of the same data.

**Comment by grisaitis** [comment]
I think this is a great idea. 

As for naming, I also think a single datatype makes sense. All of these data types are just different representations of the same thing. Sort of like accessing `roi`s, there can be different endpoints for each representation of the same data instance:
* instead of `labelblk`, there could be `/<uuid>/<label_name>/block` or `/raw`, like grayscale images
* instead of `labelvol`: `/<uuid>/<label_name>/bodies` or `/volume`

And when creating the data instance, the user could specify whether they want a block-volume pair to be persisted. E.g. calling `/<uuid>/instance` with body `{"dataname": "...", "typename": "label", "storage_backends": ["block", "volume"]}`. If they choose not to persist a `volume`, and they try fetching it, either it can be computed on the fly from the block or a http error can be returned, like "no content" (204).

**Comment by DocSavage** [comment]
This has been addressed with new labelarray data type as of commit 76cfd222 although full split support needs a bug fix.  A new issue has been created to have the labelvol functionality optional with a flag.
