### ISSUE TITLE
posting segmentation failed to generate sparsevol

### ISSUE THREAD

**Issue by tingzhao** [janelia-flyem/dvid#153]
HTTP POST: http://emdata1.int.janelia.org:8500/api/node/ad5d/labels3/raw/0_1_2/352_384_352/3200_1600_12960?mutate=true

didn't produce sparsevol for 400643074 in the posted region.

**Comment by DocSavage** [comment]
Ting, do you have a copy of the posted binary somewhere on a shared drive?  Or a sparsevol (can be JSON human-readable) of the voxel coordinate for that sparsevol?

**Comment by tingzhao** [comment]
I just read the labels from the same region and posted them back.

**Comment by DocSavage** [comment]
After looking at the code, it seems the labelvol sync code is too smart for its own good.  It compares the "mutated" block with the old block and only makes changes if they are different.  Since the original issue was a bad sparsevol POST that wasn't properly constrained, and a subsequent failed denormalization, it won't clear up the discrepancy.  I'll have to add another mechanism to force a resync, or perhaps we change it so that mutate will delete and recreate regardless of what's been there before.

**Comment by DocSavage** [comment]
Other option since this is just a quick fix due to prior bug: you can modify the label of the problem area in the block to a new unique id, POST with mutate=true, then modify it back to what you want and POST again.  This will force any associated sparsevol to be updated.

**Comment by DocSavage** [comment]
Ting chose to do simple modify/post/relabel/post method to fix.
