### ISSUE TITLE
Ingesting data into DVID

### ISSUE THREAD

**Issue by unidesigner** [janelia-flyem/dvid#164]
What is currently the most efficient way/recommended way to ingest multi-terabyte datasets into DVID? How to control ingestion parallelism?

I see currently two possible ways
1. Using custom libdvid scripts
2. Using command line load.

As far as I see for 1), one can load as much data into memory before pushing to DVID. The dimensions seem to require to be blocksize-aligned. I'd assume that going through the HTTP API is not really the bottleneck, and the limiting operations are mostly IO.

As far as I see for 2), the the dvid load command still works, but has not option to control parallelism e.g. spawning multiple read/write threads? A small issue I found with this is that if I invoke:
 `dvid -rpc=:8041 node 5b grayscale load 0,0,0 "/path/to/my/*.tif"`
I get a `
2016/06/21 16:34:14 gorpc.Client: [:8041]. Cannot obtain response during timeout=20s
RPC error for "node 5b grayscale load 0,0,0 /path/to/my/*.tif": gorpc.Client: [:8041]. Cannot obtain response during timeout=20s`
but looking at the log, DVID started to ingest images one-by-one in the background. Not sure what the RPC error exactly means.

Thanks for advice.

**Comment by DocSavage** [comment]
Add a separate issue for timeout response error on RPC.  This occurred when I went from the old builtin Go rpc library to the more optimized [gorpc package](https://github.com/valyala/gorpc).  It shouldn't affect the load command.  

Ingestion will always be disk I/O limited, depending on the storage engine.  With the default embedded leveldb, you won't get benefit from massive parallelism (and it might thrash the disk) if it's going to a single drive.  So the current "load" command works ok for embedded leveldb but could be tuned better so there's no deadspots.  It doesn't work well for very scalable backends like Google Cloud Storage.

If there's a big store backend, you can write data from multiple processes into the store directly, bypassing DVID except for getting the necessary key.  We do this when ingesting massive tile data into our Scality store, and use the ["tilekey" endpoint](https://github.com/janelia-flyem/dvid/blob/master/datatype/imagetile/imagetile.go#L235) for getting the needed key so DVID can later access the ingested data.  When doing it this way, you need to know the DVID-specific keys and also set any metadata (e.g., tile extents).  We are experimenting with this approach in a datatype-by-datatype fashion.  We are also experimenting with having multiple DVID frontends storing to a common shared store, setting metadata appropriately afterwards.  This can be more difficult for label data that is denormalized into several formats (sparse volumes, label blocks, label-aware annotations).  But for simple immutable grayscale, it works well.

Our segmentation processes currently use POST 3d raw with aligned blocks and lz4 compression to decrease the amount of traffic.  Ideally, using the "blocks" endpoint should be fastest because it minimizes the work DVID does, basically making it a small layer over the store I/O.

Speeding up ingestion is something we'd like to do and have a bunch of ideas, including the [eventual DVID Store](https://github.com/janelia-flyem/dvid/wiki/DVID-Store) that shouldn't need the compaction cycles of leveldb.  As FlyEM moves into larger imaging volumes, we're going to spend more time optimizing ingestion.

**Comment by stephenplaza** [comment]
I should also point out that FlyEM currently does most of its ingestion (grayscale and segmentation) using DVIDSparkServices (https://github.com/janelia-flyem/DVIDSparkServices).  Ingestion performance (for grayscale blocks) seems comparable to single process (since not much compute is requred) but you can use the same set of scripts when DVID has a backend of something distributed (like Google buckets).

**Comment by unidesigner** [comment]
Thanks for the detailed reply, this is very helpful. I will test these different options further for our use case.

**Comment by DocSavage** [comment]
I've updated the [Tile Generation wiki page](https://github.com/janelia-flyem/dvid/wiki/Tile-Generation) to reflect how we scale up tile ingestion, so it's not bottlenecked by a single DVID server if you have a distributed store.

**Comment by DocSavage** [comment]
We will be testing the new [badger kv store](https://github.com/dgraph-io/badger) soon.  It is based on the WiscKey database paper where values go into an append-only log and should only need to be compacted if there are deletes or rewrites.  This should greatly speed up ingestion.

I'm closing this issue and may add a separate wiki page on Ingestion.
