### ISSUE TITLE
Revise volume creation parameters for REST API

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#17]
Right now the parameters used to create a new volume in dvid are not well documented.  But beyond that, it would be nice if the client could specify exactly what the datatype of the pixels are.  For example, all of the information in the `metadata` json should be provided when creating a new volume.

This would require at least the following enhancements:
- DVID needs to support `voxels` data with an arbitrary number of channels (currently the client is limited to the predefined datatypes, e.g. `grayscale8`, `rgba8`).
- DVID needs to support `float32` as a pixel type

**Comment by DocSavage** [comment]
Rather than have a generic datatype for all kinds of voxel data, DVID opts to explicitly have types for each: "uint8blk" for uint8/voxel and "rgba8blk" for RGBA/voxel.  Label data is a special case of uint64/voxel and the API is accordingly different.  Since each datatype is explicit about what data format it supports, there is no need for a POST to a data instance to specify something like the metadata.

If we create a generic voxel datatype, then such a metadata would be necessary, but much as the Go language lacks generics, the DVID data types do as well.  This might cause more code copying but also allows fine-tuning based on the actually used data as well as adjustments to the API, as in the labels case.
