### ISSUE TITLE
Annotation datatype, elements not syncing with labelmap

### ISSUE THREAD

**Issue by umayaml** [janelia-flyem/dvid#325]
Been noticing that occasionally, when a labelmap segmentation is mutated and if the segmentation is sync to an annotation datatype, that the elements might not sync correctly. We saw this issue a few months ago and it was resolved but I'm seeing it again the past few weeks.

**Comment by DocSavage** [comment]
@umayaml Do you have any specific labels where this occurred?  Assume this is production server, but if you could give UUID maybe I can use it as a test case.

**Comment by DocSavage** [comment]
Recent commits hopefully resolve this issue.
1) Mutations could have occurred while the label maps were loading, but now the HTTP API is not enabled until the label map is fully loaded.  (commit 02806d0)
2) Synced annotations that rely on any label-based data could have data changed underneath them due to slight delay.  It's a race condition, so it was changed to rely on supervoxels, which are immutable unless being split or mutated.  (commit aec633)
