### ISSUE TITLE
Store keyvalue instance log to disk

### ISSUE THREAD

**Issue by stuarteberg** [janelia-flyem/dvid#391]
Right now, keyvalue instances can optionally be configured to write to kafka for each POST.  If I wanted to read the entire log, is kafka my only choice, or is that log also stored locally?

I'd like a local option, in case we move away from kafka (or it suffers down time due to migrations, hardware issues, etc.)

**Comment by DocSavage** [comment]
It currently is not stored locally and the keyvalue kafka record is just POST and not other ops like DELETE. However it should be straightforward to add local storage similar to how we handle labelmap mutations. However, we didn't store the value in the log because of potential size. We could do this for some instances if we knew size was small.

**Comment by DocSavage** [comment]
@stuarteberg To clarify, I think you are proposing to have local JSON mutations files similar to how we do the labelmap type, right? This is different than the protobuf-encoded storage of mutation ops.

**Comment by DocSavage** [comment]
Also I'm not sure if this is something we want working for all `keyvalue` instances by default?

**Comment by DocSavage** [comment]
Fixed in commit `ab92fb`.
